/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.clevetec.plugin;

import org.gradle.api.Project;
import org.gradle.api.Plugin;
import ru.clevetec.plugin.tasks.CheckConnectionToDB;
import ru.clevetec.plugin.tasks.CreateTable;
import ru.clevetec.plugin.tasks.InsertDataIntoTable;

public class DbJavaPluginPlugin implements Plugin<Project> {
    public void apply(Project project) {

        project.getTasks().register("checkConnection", CheckConnectionToDB.class, task -> {
            task.setGroup("db");
        });
        project.getTasks().register("createTable", CreateTable.class, task -> {
            task.dependsOn("checkConnection");
            task.setGroup("db");
        });
        project.getTasks().register("insertData", InsertDataIntoTable.class, task -> {
            task.dependsOn("checkConnection");
            task.setGroup("db");
        });

    }
}
